# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('op1', models.CharField(max_length=1000)),
                ('op2', models.CharField(max_length=1000)),
                ('op3', models.CharField(max_length=1000)),
                ('op4', models.CharField(max_length=1000)),
                ('ans', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default=1800)),
                ('array', models.CharField(default='1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19;20', max_length=800)),
            ],
        ),
    ]
